name: deploy
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: "deploy to production"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          cat >>~/.ssh/config << END
          Host prod
            HostName $SSH_HOST
            User $SSH_USERNAME
            Port $SSH_PORT
            IdentityFile ~/.ssh/authorized_keys
            StrictHostKeyChecking no
          END
        env:
          SSH_USERNAME: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_PORT: 22
      - name: update sabine
        run:
          ssh prod 'bash -i -c "cd sabine"'
          ssh prod 'bash -i -c "git pull"'
          ssh prod 'bash -i -c "npm i"'
          ssh prod 'bash -i -c "pm2 restart sabine"'